FORMAT: 1A

# Collections Data Service

A simple API allowing clients to retrieve collections data from the Art Institute of Chicago.

# Group Artworks

Endpoints to retrieve artwork data

## Artwork [/v1/artworks/{artwork_id}]

### View an Artwork detail [GET]

+ Parameters
    + artwork_id: `111628` (number) - ID of the Artwork

+ Response 200 (application/json)
    + Attributes
        + data (Artwork)

### Artwork not found [GET]

+ Parameters
    + artwork_id: `234234298734298374` (number) - ID of the Artwork

+ Response 404 (application/json)
    + Attributes (Error)
      
### Bad Artwork ID [GET]

+ Parameters
    + artwork_id: `sdfsdf` (number) - ID of the Artwork

+ Response 400 (application/json)
    + Attributes (Error)
      
### Can't POST [POST]

+ Parameters
    + artwork_id: `111628` (number) - ID of the Artwork

+ Response 405 (application/json)
    + Attributes (Error)


## Artwork [/v1/artworks/?ids={artwork_ids}]

### View an Artwork detail [GET]

+ Parameters
    + artwork_ids: `111628,79307` (string) - IDs of the Artwork

+ Response 200 (application/json)
    + Attributes
        + pagination (Pagination)
        + data (array[Artwork])


## Artwork [/v1/artworks]

### View all Artworks [GET]

+ Response 200 (application/json)
    + Attributes
        + pagination (Pagination)
        + data (array[Artwork])
      
### Can't POST [POST]

+ Response 405 (application/json)
    + Attributes (Error)









# Group Artists

Endpoints to retrieve artist data

## Artist [/v1/artists/{artist_id}]

### View an Artist detail [GET]

+ Parameters
    + artwork_id: `27823` (number) - ID of the Artist

+ Response 200 (application/json)
    + Attributes
        + data (Artist)

### Artist not found [GET]

+ Parameters
    + artist_id: `234234298734298374` (number) - ID of the Artist

+ Response 404 (application/json)
    + Attributes (Error)
      
### Bad Artist ID [GET]

+ Parameters
    + artist_id: `sdfsdf` (number) - ID of the Artist

+ Response 400 (application/json)
    + Attributes (Error)
      
### Can't POST [POST]

+ Parameters
    + artist_id: `27823` (number) - ID of the Artist

+ Response 405 (application/json)
    + Attributes (Error)


## Artwork [/v1/artists/?ids={artist_ids}]

### View an Artist detail [GET]

+ Parameters
    + artist_ids: `27823,9287` (string) - IDs of the Artist

+ Response 200 (application/json)
    + Attributes
        + pagination (Pagination)
        + data (array[Artist])


## Artwork [/v1/artists]

### View all Artists [GET]

+ Response 200 (application/json)
    + Attributes
        + pagination (Pagination)
        + data (array[Artist])
      
### Can't POST [POST]

+ Response 405 (application/json)
    + Attributes (Error)





# Group Galleries

Endpoints to retrieve gallery data

## Gallery [/v1/galleries/{gallery_id}]

### View an Gallery detail [GET]

+ Parameters
    + gallery_id: `2147483604` (number) - ID of the Gallery

+ Response 200 (application/json)
    + Attributes
        + data (Gallery)

### Gallery not found [GET]

+ Parameters
    + gallery_id: `234234298734298374` (number) - ID of the Gallery

+ Response 404 (application/json)
    + Attributes (Error)
      
### Bad Gallery ID [GET]

+ Parameters
    + gallery_id: `sdfsdf` (number) - ID of the Gallery

+ Response 400 (application/json)
    + Attributes (Error)
      
### Can't POST [POST]

+ Parameters
    + gallery_id: `27823` (number) - ID of the Gallery

+ Response 405 (application/json)
    + Attributes (Error)


## Artwork [/v1/galleries/?ids={gallery_ids}]

### View an Gallery detail [GET]

+ Parameters
    + gallery_ids: `2147483604,2147477833` (string) - IDs of the Galleries

+ Response 200 (application/json)
    + Attributes
        + pagination (Pagination)
        + data (array[Gallery])
        

## Gallery [/v1/galleries]

### View all Galleries [GET]

+ Response 200 (application/json)
    + Attributes
        + pagination (Pagination)
        + data (array[Gallery])
      
### Can't POST [POST]

+ Response 405 (application/json)
    + Attributes (Error)





## Data Structures

### Artwork
+ id (number, required)
+ title (string)
+ ids (object)
+ titles (object)
+ dates (object)
+ creator (object)
+ department (object)
+ dimensions (string)
+ medium (object)
+ inscriptions (array[string])
+ credit_line (string)
+ history (object)
+ created_at (string)
+ created_by (string)
+ modified_at (string)
+ modified_by (string)

### Artist
+ id (number, required)
+ title (string)
+ ids (object)
+ titles (object)
+ created_at (string)
+ created_by (string)
+ modified_at (string)
+ modified_by (string)

### Gallery
+ id (number, required)
+ title (string)
+ ids (object)
+ titles (object)
+ closed (boolean)
+ number (number)
+ created_at (string)
+ created_by (string)
+ modified_at (string)
+ modified_by (string)

### Error
+ status (number)
+ error (string, required)
+ detail (string)

### Pagination
+ results (object, required)
+ pages (object, required)
+ links (object, required)
