FORMAT: 1A
HOST: http://127.0.0.1:9393

# Collections Data Service

A simple API allowing clients to retrieve collections data from the Art Institute of Chicago.







# Group Artists

Endpoints to retrieve artist data.




## Artist [/v1/artists/{id}]

Endpoints dealing with a single artist.


### Retrieve an Artist [GET]

+ Parameters
    + id: `40610` (number)

+ Response 200 (application/json; charset=utf-8)

    + Attributes
        + data (Artist)

+ Request Non-existent artist

    + Parameters
        + id: `9223372036854775807` (number)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (Error)


+ Request Invalid identifier

    + Parameters
        + id: `foobar` (number)

+ Response 400 (application/json; charset=utf-8)
    + Attributes (Error)



### Update an Artist [POST]

Updating artists is forbidden.

+ Parameters
    + id: `40610` (number)

+ Response 405 (application/json; charset=utf-8)
    + Attributes (Error)




## Multiple Artists [/v1/artists/?ids={ids}]

Endpoints dealing with multiple artists.


### Retrieve 2 Artists [GET]

+ Parameters
    + ids: `40610,9287` (string)

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + pagination (Pagination)
        + data (array[Artist])




## All Artists [/v1/artists]

Provides pagination. Only supports GET.


### List all Artists [GET]

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + pagination (Pagination)
        + data (array[Artist])


### Add Artists [POST]

Adding artists is forbidden.

+ Response 405 (application/json; charset=utf-8)
    + Attributes (Error)







# Group Artworks

Endpoints to retrieve artwork data.




## Artwork [/v1/artworks/{id}]

Endpoints dealing with a single artwork.


### Retrieve an Artwork [GET]

+ Parameters
    + id: `111628` (number)

+ Response 200 (application/json; charset=utf-8)

    + Attributes
        + data (Artwork)

+ Request Non-existent artwork

    + Parameters
        + id: `9223372036854775807` (number)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (Error)


+ Request Invalid identifier

    + Parameters
        + id: `foobar` (number)

+ Response 400 (application/json; charset=utf-8)
    + Attributes (Error)



### Update an Artwork [POST]

Updating artworks is forbidden.

+ Parameters
    + id: `111628` (number)

+ Response 405 (application/json; charset=utf-8)
    + Attributes (Error)




## Multiple Artworks [/v1/artworks/?ids={ids}]

Endpoints dealing with multiple artworks.


### Retrieve 2 Artworks [GET]

+ Parameters
    + ids: `111628,79307` (string)

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + pagination (Pagination)
        + data (array[Artwork])




## All Artworks [/v1/artworks]

Provides pagination. Only supports GET.


### List all Artworks [GET]

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + pagination (Pagination)
        + data (array[Artwork])


### Add Artworks [POST]

Adding artworks is forbidden.

+ Response 405 (application/json; charset=utf-8)
    + Attributes (Error)







# Group Departments

Endpoints to retrieve department data.




## Department [/v1/departments/{id}]

Endpoints dealing with a single department.


### Retrieve an Department [GET]

+ Parameters
    + id: `86` (number)

+ Response 200 (application/json; charset=utf-8)

    + Attributes
        + data (Department)

+ Request Non-existent department

    + Parameters
        + id: `9223372036854775807` (number)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (Error)


+ Request Invalid identifier

    + Parameters
        + id: `foobar` (number)

+ Response 400 (application/json; charset=utf-8)
    + Attributes (Error)



### Update an Department [POST]

Updating departments is forbidden.

+ Parameters
    + id: `86` (number)

+ Response 405 (application/json; charset=utf-8)
    + Attributes (Error)




## Multiple Departments [/v1/departments/?ids={ids}]

Endpoints dealing with multiple departments.


### Retrieve 2 Departments [GET]

+ Parameters
    + ids: `86,941` (string)

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + pagination (Pagination)
        + data (array[Department])




## All Departments [/v1/departments]

Provides pagination. Only supports GET.


### List all Departments [GET]

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + pagination (Pagination)
        + data (array[Department])


### Add Departments [POST]

Adding departments is forbidden.

+ Response 405 (application/json; charset=utf-8)
    + Attributes (Error)







# Group Galleries

Endpoints to retrieve gallery data.




## Gallery [/v1/galleries/{id}]

Endpoints dealing with a single gallery.


### Retrieve an Gallery [GET]

+ Parameters
    + id: `2147483604` (number)

+ Response 200 (application/json; charset=utf-8)

    + Attributes
        + data (Gallery)

+ Request Non-existent gallery

    + Parameters
        + id: `9223372036854775807` (number)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (Error)


+ Request Invalid identifier

    + Parameters
        + id: `foobar` (number)

+ Response 400 (application/json; charset=utf-8)
    + Attributes (Error)



### Update an Gallery [POST]

Updating galleries is forbidden.

+ Parameters
    + id: `2147483604` (number)

+ Response 405 (application/json; charset=utf-8)
    + Attributes (Error)




## Multiple Galleries [/v1/galleries/?ids={ids}]

Endpoints dealing with multiple galleries.


### Retrieve 2 Galleries [GET]

+ Parameters
    + ids: `2147483604,2147477833` (string)

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + pagination (Pagination)
        + data (array[Gallery])




## All Galleries [/v1/galleries]

Provides pagination. Only supports GET.


### List all Galleries [GET]

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + pagination (Pagination)
        + data (array[Gallery])


### Add Galleries [POST]

Adding galleries is forbidden.

+ Response 405 (application/json; charset=utf-8)
    + Attributes (Error)







## Data Structures

### Artwork
+ id (number, required)
+ title (string)
+ ids (object)
+ titles (object)
+ dates (object)
+ creator (object)
+ department (object)
+ dimensions (string)
+ medium (object)
+ inscriptions (string)
+ credit_line (string)
+ history (object)
+ created_at (string)
+ created_by (string)
+ modified_at (string)
+ modified_by (string)

### Artist
+ id (number, required)
+ title (string)
+ ids (object)
+ titles (object)
+ dates (object)
  + birth (required)
  + death (required)
+ created_at (string)
+ created_by (string)
+ modified_at (string)
+ modified_by (string)

### Gallery
+ id (number, required)
+ title (string)
+ ids (object)
+ titles (object)
+ closed (boolean)
+ number (number)
+ floor (number)
+ created_at (string)
+ created_by (string)
+ modified_at (string)
+ modified_by (string)

### Department
+ id (number, required)
+ title (string)
+ ids (object)
+ titles (object)
+ created_at (string)
+ created_by (string)
+ modified_at (string)
+ modified_by (string)


### Error
+ status (number)
+ error (string, required)
+ detail (string)

### Pagination
+ results (object, required)
+ pages (object, required)
+ links (object, required)
