## Data Structures

### Artwork
+ id (number, required)
+ title (string)
+ ids (object)
+ titles (object)
+ dates (object)
+ creator (object)
+ department (object)
+ dimensions (string)
+ medium (object)
+ inscriptions (string)
+ credit_line (string)
+ history (object)
+ created_at (string)
+ created_by (string)
+ modified_at (string)
+ modified_by (string)

### Artist
+ id (number, required)
+ title (string)
+ ids (object)
+ titles (object)
+ dates (object)
  + birth (required)
  + death (required)
+ created_at (string)
+ created_by (string)
+ modified_at (string)
+ modified_by (string)

### Gallery
+ id (number, required)
+ title (string)
+ ids (object)
+ titles (object)
+ closed (boolean)
+ number (number)
+ floor (number)
+ created_at (string)
+ created_by (string)
+ modified_at (string)
+ modified_by (string)

### Department
+ id (number, required)
+ title (string)
+ ids (object)
+ titles (object)
+ created_at (string)
+ created_by (string)
+ modified_at (string)
+ modified_by (string)


### Error
+ status (number)
+ error (string, required)
+ detail (string)

### Pagination
+ results (object, required)
+ pages (object, required)
+ links (object, required)
