## Data Structures

### Common
+ id (number)
+ title (required)
+ citi_id (number, required)
+ lake_guid (required)
+ lake_uri (required)
+ created_at (required)
+ modified_at (required)
+ indexed_at (required)

### Artwork
+ Include Common
+ date_display (required)
+ date_start (number, required)
+ date_end (number, required)
+ creator_id (number, required)
+ creator_display (required)
+ image_guid (required)
+ location (required)
+ department_id (number, required)
+ dimensions (required)
+ medium (required)
+ credit_line (required)
+ copyright (nullable, required)
+ inscriptions (nullable, required)
+ publications (nullable, required)
+ provenance (nullable, required)
+ category_ids (array, required)
+ document_guids (array, required)

### Artist
+ Include Common
+ date_birth (number, required)
+ date_death (number, required)

### Gallery
+ Include Common
+ closed (boolean, required)
+ number (required)
+ floor (required)
+ latitude (number, required)
+ longitude (number, required)

### Department
+ Include Common

### Category
+ Include Common
+ description (string, required)
+ is_in_nav (boolean, required)
+ parent_id (number, nullable, required)
+ sort (number, required)
+ type (number, required)

<!-- TODO: Fix capitalization in generation -->
### Agenttype
+ Include Common

### Curriculum
+ Include Common

### Gradelevel
+ Include Common

### Error
+ status (number)
+ error (string, required)
+ detail (string)

### Pagination
+ results (object, required)
+ pages (object, required)
+ links (object, required)
