# Group Artists

Endpoints to retrieve artist data.




## Artist [/v1/artists/{id}]

Endpoints dealing with a single artist.


### Retrieve an Artist [GET]

+ Parameters
    + id: `27823` (number)

+ Response 200 (application/json; charset=utf-8)

    + Attributes
        + data (Artist)

+ Request Non-existent artist

    + Parameters
        + id: `9223372036854775807` (number)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (Error)


+ Request Invalid identifier

    + Parameters
        + id: `foobar` (number)

+ Response 400 (application/json; charset=utf-8)
    + Attributes (Error)



### Update an Artist [POST]

Updating artists is forbidden.

+ Parameters
    + id: `27823` (number)

+ Response 405 (application/json; charset=utf-8)
    + Attributes (Error)




## Multiple Artists [/v1/artists/?ids={ids}]

Endpoints dealing with multiple artists.


### Retrieve 2 Artists [GET]

+ Parameters
    + ids: `27823,9287` (string)

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + pagination (Pagination)
        + data (array[Artist])




## All Artists [/v1/artists]

Provides pagination. Only supports GET.


### List all Artists [GET]

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + pagination (Pagination)
        + data (array[Artist])


### Add Artists [POST]

Adding artists is forbidden.

+ Response 405 (application/json; charset=utf-8)
    + Attributes (Error)
