# Group Galleries

Endpoints to retrieve gallery data.




## Gallery [/v1/galleries/{id}]

Endpoints dealing with a single gallery.


### Retrieve an Gallery [GET]

+ Parameters
    + id: `2147483604` (number)

+ Response 200 (application/json; charset=utf-8)

    + Attributes
        + data (Gallery)

+ Request Non-existent gallery

    + Parameters
        + id: `9223372036854775807` (number)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (Error)


+ Request Invalid identifier

    + Parameters
        + id: `foobar` (number)

+ Response 400 (application/json; charset=utf-8)
    + Attributes (Error)



### Update an Gallery [POST]

Updating galleries is forbidden.

+ Parameters
    + id: `2147483604` (number)

+ Response 405 (application/json; charset=utf-8)
    + Attributes (Error)




## Multiple Galleries [/v1/galleries/?ids={ids}]

Endpoints dealing with multiple galleries.


### Retrieve 2 Galleries [GET]

+ Parameters
    + ids: `2147483604,2147477833` (string)

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + pagination (Pagination)
        + data (array[Gallery])




## All Galleries [/v1/galleries]

Provides pagination. Only supports GET.


### List all Galleries [GET]

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + pagination (Pagination)
        + data (array[Gallery])


### Add Galleries [POST]

Adding galleries is forbidden.

+ Response 405 (application/json; charset=utf-8)
    + Attributes (Error)
